-- CreateTable
CREATE TABLE "ClaimsLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "dropId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "claimedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
